
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb  2 2026 14:56:08 IST (Feb  2 2026 09:26:08 UTC)

// Verification Directory fv/fifo 

module fifo(clk, reset, data_in, r, w, data_out, full, empty);
  input clk, reset, r, w;
  input [7:0] data_in;
  output [7:0] data_out;
  output full, empty;
  wire clk, reset, r, w;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire full, empty;
  wire [7:0] \fifo_memory[1] ;
  wire [7:0] \fifo_memory[5] ;
  wire [7:0] \fifo_memory[4] ;
  wire [7:0] \fifo_memory[0] ;
  wire [7:0] \fifo_memory[2] ;
  wire [7:0] \fifo_memory[7] ;
  wire [7:0] \fifo_memory[6] ;
  wire [2:0] read_count;
  wire [7:0] \fifo_memory[3] ;
  wire [3:0] fifo_count;
  wire [2:0] write_count;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_33, n_34, n_35;
  wire n_37, n_38, n_41, n_42, n_43, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_55, n_57;
  wire n_58, n_59, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_144, n_145, n_146;
  DFFQX2 \data_out_reg[0] (.CK (clk), .D (n_134), .Q (data_out[0]));
  DFFQX2 \data_out_reg[2] (.CK (clk), .D (n_132), .Q (data_out[2]));
  DFFQX2 \data_out_reg[3] (.CK (clk), .D (n_137), .Q (data_out[3]));
  DFFQX2 \data_out_reg[7] (.CK (clk), .D (n_139), .Q (data_out[7]));
  DFFQX2 \data_out_reg[4] (.CK (clk), .D (n_133), .Q (data_out[4]));
  DFFQX2 \data_out_reg[1] (.CK (clk), .D (n_136), .Q (data_out[1]));
  DFFQX2 \data_out_reg[5] (.CK (clk), .D (n_138), .Q (data_out[5]));
  DFFQX2 \data_out_reg[6] (.CK (clk), .D (n_135), .Q (data_out[6]));
  NAND4XL g3321__2398(.A (n_126), .B (n_87), .C (n_102), .D (n_119), .Y
       (n_139));
  NAND4XL g3320__5107(.A (n_106), .B (n_85), .C (n_88), .D (n_111), .Y
       (n_138));
  NAND4XL g3316__6260(.A (n_90), .B (n_109), .C (n_91), .D (n_114), .Y
       (n_137));
  NAND4XL g3317__4319(.A (n_96), .B (n_94), .C (n_107), .D (n_117), .Y
       (n_136));
  NAND4XL g3318__8428(.A (n_105), .B (n_84), .C (n_95), .D (n_113), .Y
       (n_135));
  NAND4XL g3315__5526(.A (n_86), .B (n_100), .C (n_99), .D (n_127), .Y
       (n_134));
  NAND4XL g3314__6783(.A (n_92), .B (n_108), .C (n_93), .D (n_124), .Y
       (n_133));
  NAND4XL g3319__3680(.A (n_103), .B (n_89), .C (n_116), .D (n_112), .Y
       (n_132));
  SDFFQXL \fifo_memory_reg[1][2] (.CK (clk), .D (\fifo_memory[1] [2]),
       .SI (data_in[2]), .SE (n_130), .Q (\fifo_memory[1] [2]));
  SDFFQXL \fifo_memory_reg[5][5] (.CK (clk), .D (data_in[5]), .SI
       (\fifo_memory[5] [5]), .SE (n_131), .Q (\fifo_memory[5] [5]));
  SDFFQXL \fifo_memory_reg[5][6] (.CK (clk), .D (data_in[6]), .SI
       (\fifo_memory[5] [6]), .SE (n_131), .Q (\fifo_memory[5] [6]));
  SDFFQXL \fifo_memory_reg[5][7] (.CK (clk), .D (data_in[7]), .SI
       (\fifo_memory[5] [7]), .SE (n_131), .Q (\fifo_memory[5] [7]));
  SDFFQXL \fifo_memory_reg[1][0] (.CK (clk), .D (\fifo_memory[1] [0]),
       .SI (data_in[0]), .SE (n_130), .Q (\fifo_memory[1] [0]));
  SDFFQXL \fifo_memory_reg[1][1] (.CK (clk), .D (\fifo_memory[1] [1]),
       .SI (data_in[1]), .SE (n_130), .Q (\fifo_memory[1] [1]));
  SDFFQXL \fifo_memory_reg[1][3] (.CK (clk), .D (\fifo_memory[1] [3]),
       .SI (data_in[3]), .SE (n_130), .Q (\fifo_memory[1] [3]));
  SDFFQXL \fifo_memory_reg[5][4] (.CK (clk), .D (data_in[4]), .SI
       (\fifo_memory[5] [4]), .SE (n_131), .Q (\fifo_memory[5] [4]));
  SDFFQXL \fifo_memory_reg[5][3] (.CK (clk), .D (data_in[3]), .SI
       (\fifo_memory[5] [3]), .SE (n_131), .Q (\fifo_memory[5] [3]));
  SDFFQXL \fifo_memory_reg[1][5] (.CK (clk), .D (\fifo_memory[1] [5]),
       .SI (data_in[5]), .SE (n_130), .Q (\fifo_memory[1] [5]));
  SDFFQXL \fifo_memory_reg[1][6] (.CK (clk), .D (\fifo_memory[1] [6]),
       .SI (data_in[6]), .SE (n_130), .Q (\fifo_memory[1] [6]));
  SDFFQXL \fifo_memory_reg[1][7] (.CK (clk), .D (\fifo_memory[1] [7]),
       .SI (data_in[7]), .SE (n_130), .Q (\fifo_memory[1] [7]));
  SDFFQXL \fifo_memory_reg[4][6] (.CK (clk), .D (\fifo_memory[4] [6]),
       .SI (data_in[6]), .SE (n_129), .Q (\fifo_memory[4] [6]));
  SDFFQXL \fifo_memory_reg[4][1] (.CK (clk), .D (\fifo_memory[4] [1]),
       .SI (data_in[1]), .SE (n_129), .Q (\fifo_memory[4] [1]));
  SDFFQXL \fifo_memory_reg[4][2] (.CK (clk), .D (\fifo_memory[4] [2]),
       .SI (data_in[2]), .SE (n_129), .Q (\fifo_memory[4] [2]));
  SDFFQXL \fifo_memory_reg[4][3] (.CK (clk), .D (\fifo_memory[4] [3]),
       .SI (data_in[3]), .SE (n_129), .Q (\fifo_memory[4] [3]));
  SDFFQXL \fifo_memory_reg[4][4] (.CK (clk), .D (\fifo_memory[4] [4]),
       .SI (data_in[4]), .SE (n_129), .Q (\fifo_memory[4] [4]));
  SDFFQXL \fifo_memory_reg[4][5] (.CK (clk), .D (\fifo_memory[4] [5]),
       .SI (data_in[5]), .SE (n_129), .Q (\fifo_memory[4] [5]));
  SDFFQXL \fifo_memory_reg[4][0] (.CK (clk), .D (\fifo_memory[4] [0]),
       .SI (data_in[0]), .SE (n_129), .Q (\fifo_memory[4] [0]));
  SDFFQXL \fifo_memory_reg[4][7] (.CK (clk), .D (\fifo_memory[4] [7]),
       .SI (data_in[7]), .SE (n_129), .Q (\fifo_memory[4] [7]));
  SDFFQXL \fifo_memory_reg[5][0] (.CK (clk), .D (data_in[0]), .SI
       (\fifo_memory[5] [0]), .SE (n_131), .Q (\fifo_memory[5] [0]));
  SDFFQXL \fifo_memory_reg[5][1] (.CK (clk), .D (data_in[1]), .SI
       (\fifo_memory[5] [1]), .SE (n_131), .Q (\fifo_memory[5] [1]));
  SDFFQXL \fifo_memory_reg[5][2] (.CK (clk), .D (data_in[2]), .SI
       (\fifo_memory[5] [2]), .SE (n_131), .Q (\fifo_memory[5] [2]));
  SDFFQXL \fifo_memory_reg[1][4] (.CK (clk), .D (\fifo_memory[1] [4]),
       .SI (data_in[4]), .SE (n_130), .Q (\fifo_memory[1] [4]));
  SDFFQXL \fifo_memory_reg[0][2] (.CK (clk), .D (\fifo_memory[0] [2]),
       .SI (data_in[2]), .SE (n_128), .Q (\fifo_memory[0] [2]));
  SDFFQXL \fifo_memory_reg[0][1] (.CK (clk), .D (\fifo_memory[0] [1]),
       .SI (data_in[1]), .SE (n_128), .Q (\fifo_memory[0] [1]));
  SDFFQXL \fifo_memory_reg[0][0] (.CK (clk), .D (\fifo_memory[0] [0]),
       .SI (data_in[0]), .SE (n_128), .Q (\fifo_memory[0] [0]));
  SDFFQXL \fifo_memory_reg[0][3] (.CK (clk), .D (\fifo_memory[0] [3]),
       .SI (data_in[3]), .SE (n_128), .Q (\fifo_memory[0] [3]));
  SDFFQXL \fifo_memory_reg[0][6] (.CK (clk), .D (\fifo_memory[0] [6]),
       .SI (data_in[6]), .SE (n_128), .Q (\fifo_memory[0] [6]));
  SDFFQXL \fifo_memory_reg[0][5] (.CK (clk), .D (\fifo_memory[0] [5]),
       .SI (data_in[5]), .SE (n_128), .Q (\fifo_memory[0] [5]));
  SDFFQXL \fifo_memory_reg[0][4] (.CK (clk), .D (\fifo_memory[0] [4]),
       .SI (data_in[4]), .SE (n_128), .Q (\fifo_memory[0] [4]));
  SDFFQXL \fifo_memory_reg[0][7] (.CK (clk), .D (\fifo_memory[0] [7]),
       .SI (data_in[7]), .SE (n_128), .Q (\fifo_memory[0] [7]));
  AOI222XL g3377__1617(.A0 (\fifo_memory[2] [0]), .A1 (n_118), .B0
       (data_out[0]), .B1 (n_122), .C0 (n_144), .C1 (\fifo_memory[0]
       [0]), .Y (n_127));
  AOI22X1 g3431__2802(.A0 (\fifo_memory[0] [7]), .A1 (n_144), .B0
       (\fifo_memory[4] [7]), .B1 (n_123), .Y (n_126));
  AOI222XL g3378__1705(.A0 (\fifo_memory[1] [4]), .A1 (n_110), .B0
       (\fifo_memory[4] [4]), .B1 (n_123), .C0 (n_122), .C1
       (data_out[4]), .Y (n_124));
  SDFFQXL \fifo_memory_reg[7][2] (.CK (clk), .D (data_in[2]), .SI
       (\fifo_memory[7] [2]), .SE (n_120), .Q (\fifo_memory[7] [2]));
  SDFFQXL \fifo_memory_reg[6][2] (.CK (clk), .D (data_in[2]), .SI
       (\fifo_memory[6] [2]), .SE (n_121), .Q (\fifo_memory[6] [2]));
  SDFFQXL \fifo_memory_reg[6][7] (.CK (clk), .D (data_in[7]), .SI
       (\fifo_memory[6] [7]), .SE (n_121), .Q (\fifo_memory[6] [7]));
  SDFFQXL \fifo_memory_reg[7][7] (.CK (clk), .D (data_in[7]), .SI
       (\fifo_memory[7] [7]), .SE (n_120), .Q (\fifo_memory[7] [7]));
  SDFFQXL \fifo_memory_reg[6][0] (.CK (clk), .D (data_in[0]), .SI
       (\fifo_memory[6] [0]), .SE (n_121), .Q (\fifo_memory[6] [0]));
  SDFFQXL \fifo_memory_reg[6][1] (.CK (clk), .D (data_in[1]), .SI
       (\fifo_memory[6] [1]), .SE (n_121), .Q (\fifo_memory[6] [1]));
  SDFFQXL \fifo_memory_reg[6][3] (.CK (clk), .D (data_in[3]), .SI
       (\fifo_memory[6] [3]), .SE (n_121), .Q (\fifo_memory[6] [3]));
  SDFFQXL \fifo_memory_reg[6][4] (.CK (clk), .D (data_in[4]), .SI
       (\fifo_memory[6] [4]), .SE (n_121), .Q (\fifo_memory[6] [4]));
  SDFFQXL \fifo_memory_reg[6][5] (.CK (clk), .D (data_in[5]), .SI
       (\fifo_memory[6] [5]), .SE (n_121), .Q (\fifo_memory[6] [5]));
  SDFFQXL \fifo_memory_reg[7][3] (.CK (clk), .D (data_in[3]), .SI
       (\fifo_memory[7] [3]), .SE (n_120), .Q (\fifo_memory[7] [3]));
  SDFFQXL \fifo_memory_reg[7][0] (.CK (clk), .D (data_in[0]), .SI
       (\fifo_memory[7] [0]), .SE (n_120), .Q (\fifo_memory[7] [0]));
  SDFFQXL \fifo_memory_reg[7][1] (.CK (clk), .D (data_in[1]), .SI
       (\fifo_memory[7] [1]), .SE (n_120), .Q (\fifo_memory[7] [1]));
  SDFFQXL \fifo_memory_reg[6][6] (.CK (clk), .D (data_in[6]), .SI
       (\fifo_memory[6] [6]), .SE (n_121), .Q (\fifo_memory[6] [6]));
  DFFQX1 \read_count_reg[2] (.CK (clk), .D (n_81), .Q (read_count[2]));
  AOI222XL g3383__5122(.A0 (n_122), .A1 (data_out[7]), .B0
       (\fifo_memory[3] [7]), .B1 (n_115), .C0 (\fifo_memory[2] [7]),
       .C1 (n_118), .Y (n_119));
  AOI222XL g3376__8246(.A0 (\fifo_memory[4] [1]), .A1 (n_123), .B0
       (data_out[1]), .B1 (n_122), .C0 (n_118), .C1 (\fifo_memory[2]
       [1]), .Y (n_117));
  AOI22X1 g3426__7098(.A0 (\fifo_memory[0] [2]), .A1 (n_144), .B0
       (\fifo_memory[3] [2]), .B1 (n_115), .Y (n_116));
  AOI222XL g3380__6131(.A0 (\fifo_memory[5] [3]), .A1 (n_101), .B0
       (\fifo_memory[2] [3]), .B1 (n_118), .C0 (n_122), .C1
       (data_out[3]), .Y (n_114));
  AOI222XL g3381__1881(.A0 (\fifo_memory[4] [6]), .A1 (n_123), .B0
       (\fifo_memory[2] [6]), .B1 (n_118), .C0 (n_122), .C1
       (data_out[6]), .Y (n_113));
  AOI222XL g3382__5115(.A0 (\fifo_memory[6] [2]), .A1 (n_104), .B0
       (data_out[2]), .B1 (n_122), .C0 (n_118), .C1 (\fifo_memory[2]
       [2]), .Y (n_112));
  AOI222XL g3379__7482(.A0 (\fifo_memory[1] [5]), .A1 (n_110), .B0
       (\fifo_memory[2] [5]), .B1 (n_118), .C0 (n_122), .C1
       (data_out[5]), .Y (n_111));
  AOI22X1 g3400__4733(.A0 (\fifo_memory[0] [3]), .A1 (n_144), .B0
       (\fifo_memory[4] [3]), .B1 (n_123), .Y (n_109));
  AOI22X1 g3401__6161(.A0 (\fifo_memory[0] [4]), .A1 (n_144), .B0
       (\fifo_memory[2] [4]), .B1 (n_118), .Y (n_108));
  AOI22X1 g3417__9315(.A0 (\fifo_memory[0] [1]), .A1 (n_144), .B0
       (\fifo_memory[1] [1]), .B1 (n_110), .Y (n_107));
  AOI22X1 g3421__9945(.A0 (\fifo_memory[0] [5]), .A1 (n_144), .B0
       (\fifo_memory[4] [5]), .B1 (n_123), .Y (n_106));
  AOI22X1 g3425__2883(.A0 (\fifo_memory[0] [6]), .A1 (n_144), .B0
       (\fifo_memory[6] [6]), .B1 (n_104), .Y (n_105));
  SDFFQXL \fifo_memory_reg[7][4] (.CK (clk), .D (data_in[4]), .SI
       (\fifo_memory[7] [4]), .SE (n_120), .Q (\fifo_memory[7] [4]));
  SDFFQXL \fifo_memory_reg[7][5] (.CK (clk), .D (data_in[5]), .SI
       (\fifo_memory[7] [5]), .SE (n_120), .Q (\fifo_memory[7] [5]));
  SDFFQXL \fifo_memory_reg[7][6] (.CK (clk), .D (data_in[6]), .SI
       (\fifo_memory[7] [6]), .SE (n_120), .Q (\fifo_memory[7] [6]));
  DFFQX1 \read_count_reg[0] (.CK (clk), .D (n_82), .Q (read_count[0]));
  DFFQX1 \read_count_reg[1] (.CK (clk), .D (n_80), .Q (read_count[1]));
  AOI22XL g3430__2346(.A0 (n_123), .A1 (\fifo_memory[4] [2]), .B0
       (n_98), .B1 (\fifo_memory[7] [2]), .Y (n_103));
  AOI22X1 g3429__1666(.A0 (\fifo_memory[1] [7]), .A1 (n_110), .B0
       (\fifo_memory[5] [7]), .B1 (n_101), .Y (n_102));
  AOI22XL g3428__7410(.A0 (n_123), .A1 (\fifo_memory[4] [0]), .B0
       (n_110), .B1 (\fifo_memory[1] [0]), .Y (n_100));
  AOI22X1 g3427__6417(.A0 (\fifo_memory[3] [0]), .A1 (n_115), .B0
       (\fifo_memory[7] [0]), .B1 (n_98), .Y (n_99));
  SDFFQX1 \fifo_memory_reg[2][0] (.CK (clk), .D (\fifo_memory[2] [0]),
       .SI (data_in[0]), .SE (n_97), .Q (\fifo_memory[2] [0]));
  SDFFQXL \fifo_memory_reg[2][1] (.CK (clk), .D (\fifo_memory[2] [1]),
       .SI (data_in[1]), .SE (n_97), .Q (\fifo_memory[2] [1]));
  SDFFQXL \fifo_memory_reg[2][2] (.CK (clk), .D (\fifo_memory[2] [2]),
       .SI (data_in[2]), .SE (n_97), .Q (\fifo_memory[2] [2]));
  SDFFQX1 \fifo_memory_reg[2][3] (.CK (clk), .D (\fifo_memory[2] [3]),
       .SI (data_in[3]), .SE (n_97), .Q (\fifo_memory[2] [3]));
  SDFFQXL \fifo_memory_reg[2][4] (.CK (clk), .D (\fifo_memory[2] [4]),
       .SI (data_in[4]), .SE (n_97), .Q (\fifo_memory[2] [4]));
  SDFFQX1 \fifo_memory_reg[2][5] (.CK (clk), .D (\fifo_memory[2] [5]),
       .SI (data_in[5]), .SE (n_97), .Q (\fifo_memory[2] [5]));
  SDFFQX1 \fifo_memory_reg[2][6] (.CK (clk), .D (\fifo_memory[2] [6]),
       .SI (data_in[6]), .SE (n_97), .Q (\fifo_memory[2] [6]));
  SDFFQX1 \fifo_memory_reg[2][7] (.CK (clk), .D (\fifo_memory[2] [7]),
       .SI (data_in[7]), .SE (n_97), .Q (\fifo_memory[2] [7]));
  DFFQX1 \fifo_count_reg[2] (.CK (clk), .D (n_77), .Q (fifo_count[2]));
  DFFQX1 \write_count_reg[1] (.CK (clk), .D (n_74), .Q
       (write_count[1]));
  DFFQX1 \fifo_count_reg[1] (.CK (clk), .D (n_76), .Q (fifo_count[1]));
  AOI22XL g3415__5477(.A0 (n_104), .A1 (\fifo_memory[6] [1]), .B0
       (n_101), .B1 (\fifo_memory[5] [1]), .Y (n_96));
  AOI22X1 g3424__2398(.A0 (\fifo_memory[1] [6]), .A1 (n_110), .B0
       (\fifo_memory[5] [6]), .B1 (n_101), .Y (n_95));
  AOI22X1 g3398__5107(.A0 (\fifo_memory[3] [1]), .A1 (n_115), .B0
       (\fifo_memory[7] [1]), .B1 (n_98), .Y (n_94));
  AOI22X1 g3399__6260(.A0 (\fifo_memory[3] [4]), .A1 (n_115), .B0
       (\fifo_memory[7] [4]), .B1 (n_98), .Y (n_93));
  AOI22XL g3402__4319(.A0 (n_104), .A1 (\fifo_memory[6] [4]), .B0
       (n_101), .B1 (\fifo_memory[5] [4]), .Y (n_92));
  AOI22X1 g3407__8428(.A0 (\fifo_memory[3] [3]), .A1 (n_115), .B0
       (\fifo_memory[7] [3]), .B1 (n_98), .Y (n_91));
  AOI22X1 g3408__5526(.A0 (\fifo_memory[1] [3]), .A1 (n_110), .B0
       (\fifo_memory[6] [3]), .B1 (n_104), .Y (n_90));
  AOI22X1 g3423__6783(.A0 (\fifo_memory[1] [2]), .A1 (n_110), .B0
       (\fifo_memory[5] [2]), .B1 (n_101), .Y (n_89));
  AOI22X1 g3416__3680(.A0 (\fifo_memory[3] [5]), .A1 (n_115), .B0
       (\fifo_memory[7] [5]), .B1 (n_98), .Y (n_88));
  AOI22XL g3418__1617(.A0 (n_104), .A1 (\fifo_memory[6] [7]), .B0
       (n_98), .B1 (\fifo_memory[7] [7]), .Y (n_87));
  AOI22XL g3419__2802(.A0 (n_104), .A1 (\fifo_memory[6] [0]), .B0
       (n_101), .B1 (\fifo_memory[5] [0]), .Y (n_86));
  AOI22XL g3420__1705(.A0 (n_104), .A1 (\fifo_memory[6] [5]), .B0
       (n_101), .B1 (\fifo_memory[5] [5]), .Y (n_85));
  AOI22X1 g3422__5122(.A0 (\fifo_memory[3] [6]), .A1 (n_115), .B0
       (\fifo_memory[7] [6]), .B1 (n_98), .Y (n_84));
  DFFQX1 \write_count_reg[0] (.CK (clk), .D (n_78), .Q
       (write_count[0]));
  DFFQX1 \write_count_reg[2] (.CK (clk), .D (n_75), .Q
       (write_count[2]));
  SDFFQXL \fifo_memory_reg[3][0] (.CK (clk), .D (data_in[0]), .SI
       (\fifo_memory[3] [0]), .SE (n_83), .Q (\fifo_memory[3] [0]));
  SDFFQXL \fifo_memory_reg[3][5] (.CK (clk), .D (data_in[5]), .SI
       (\fifo_memory[3] [5]), .SE (n_83), .Q (\fifo_memory[3] [5]));
  SDFFQXL \fifo_memory_reg[3][4] (.CK (clk), .D (data_in[4]), .SI
       (\fifo_memory[3] [4]), .SE (n_83), .Q (\fifo_memory[3] [4]));
  SDFFQXL \fifo_memory_reg[3][3] (.CK (clk), .D (data_in[3]), .SI
       (\fifo_memory[3] [3]), .SE (n_83), .Q (\fifo_memory[3] [3]));
  SDFFQX1 \fifo_memory_reg[3][7] (.CK (clk), .D (data_in[7]), .SI
       (\fifo_memory[3] [7]), .SE (n_83), .Q (\fifo_memory[3] [7]));
  SDFFQXL \fifo_memory_reg[3][1] (.CK (clk), .D (data_in[1]), .SI
       (\fifo_memory[3] [1]), .SE (n_83), .Q (\fifo_memory[3] [1]));
  SDFFQXL \fifo_memory_reg[3][6] (.CK (clk), .D (data_in[6]), .SI
       (\fifo_memory[3] [6]), .SE (n_83), .Q (\fifo_memory[3] [6]));
  NOR2XL g3405__8246(.A (reset), .B (n_72), .Y (n_82));
  NOR2XL g3404__7098(.A (reset), .B (n_71), .Y (n_81));
  NOR2XL g3403__6131(.A (reset), .B (n_68), .Y (n_80));
  SDFFQXL \fifo_memory_reg[3][2] (.CK (clk), .D (data_in[2]), .SI
       (\fifo_memory[3] [2]), .SE (n_83), .Q (\fifo_memory[3] [2]));
  AND3X1 g3444__1881(.A (write_count[2]), .B (n_58), .C (n_79), .Y
       (n_129));
  OR2X1 g3442__5115(.A (n_2), .B (n_69), .Y (n_131));
  AND3X1 g3443__7482(.A (write_count[0]), .B (n_66), .C (n_79), .Y
       (n_130));
  NOR2XL g3434__4733(.A (reset), .B (n_59), .Y (n_78));
  CLKINVX1 g3432(.A (n_73), .Y (n_77));
  OAI211X1 g3435__6161(.A0 (n_146), .A1 (n_28), .B0 (n_17), .C0 (n_51),
       .Y (n_76));
  DFFQX1 \fifo_count_reg[0] (.CK (clk), .D (n_53), .Q (fifo_count[0]));
  NOR2XL g3436__9315(.A (reset), .B (n_55), .Y (n_75));
  NOR2XL g3433__9945(.A (reset), .B (n_57), .Y (n_74));
  DFFQX1 \fifo_count_reg[3] (.CK (clk), .D (n_52), .Q (fifo_count[3]));
  AND2X1 g3445__2883(.A (n_3), .B (n_79), .Y (n_128));
  AOI221X1 g3437__1666(.A0 (fifo_count[2]), .A1 (n_43), .B0 (n_50), .B1
       (full), .C0 (n_18), .Y (n_73));
  MXI2XL g3440__7410(.A (n_47), .B (read_count[0]), .S0 (n_70), .Y
       (n_72));
  MXI2XL g3441__6417(.A (n_20), .B (read_count[2]), .S0 (n_70), .Y
       (n_71));
  INVXL g3446(.A (n_79), .Y (n_69));
  MXI2XL g3439__5477(.A (n_6), .B (read_count[1]), .S0 (n_70), .Y
       (n_68));
  NOR2X1 g3449__2398(.A (n_65), .B (n_67), .Y (n_98));
  NOR2X1 g3448__5107(.A (n_61), .B (n_67), .Y (n_115));
  OR3X1 g3464__6260(.A (n_66), .B (n_9), .C (n_62), .Y (n_121));
  NOR2X1 g3452__4319(.A (n_65), .B (n_63), .Y (n_104));
  NOR2BX1 g3453__8428(.AN (n_64), .B (n_67), .Y (n_110));
  NOR2X1 g3454__5526(.A (n_145), .B (n_63), .Y (n_123));
  OR3X1 g3462__6783(.A (n_66), .B (n_14), .C (n_62), .Y (n_120));
  NOR2X1 g3461__3680(.A (n_61), .B (n_63), .Y (n_118));
  NOR2X1 g3451__1617(.A (n_145), .B (n_67), .Y (n_101));
  MXI2XL g3458__2802(.A (n_58), .B (write_count[0]), .S0 (n_37), .Y
       (n_59));
  MXI2XL g3456__1705(.A (n_10), .B (write_count[1]), .S0 (n_37), .Y
       (n_57));
  MX2X1 g3460__5122(.A (n_15), .B (n_66), .S0 (n_37), .Y (n_55));
  NOR2XL g3447__8246(.A (write_count[1]), .B (n_62), .Y (n_79));
  OAI32X1 g3438__7098(.A0 (fifo_count[0]), .A1 (n_29), .A2 (n_38), .B0
       (n_33), .B1 (n_16), .Y (n_53));
  OAI2BB1X1 g3406__6131(.A0N (fifo_count[3]), .A1N (n_45), .B0 (n_25),
       .Y (n_52));
  AND3X1 g3463__1881(.A (n_66), .B (n_8), .C (n_49), .Y (n_97));
  AOI32X1 g3459__5115(.A0 (n_50), .A1 (n_42), .A2 (n_21), .B0
       (fifo_count[1]), .B1 (n_35), .Y (n_51));
  NAND2X1 g3455__7482(.A (n_13), .B (n_49), .Y (n_83));
  NAND3X1 g3471__4733(.A (n_48), .B (read_count[0]), .C (n_46), .Y
       (n_67));
  NAND3X1 g3472__6161(.A (n_48), .B (n_47), .C (n_46), .Y (n_63));
  CLKINVX1 g3465(.A (n_49), .Y (n_62));
  NAND2XL g3468__9315(.A (r), .B (n_46), .Y (n_70));
  OAI221X1 g3457__9945(.A0 (n_146), .A1 (n_30), .B0 (n_34), .B1
       (fifo_count[2]), .C0 (n_41), .Y (n_45));
  OAI21X1 g3466__2883(.A0 (n_146), .A1 (n_42), .B0 (n_41), .Y (n_43));
  NOR2XL g3467__2346(.A (reset), .B (n_37), .Y (n_49));
  AND2X1 g3478__1666(.A (n_24), .B (n_22), .Y (n_38));
  NAND2BX1 g3473__7410(.AN (empty), .B (n_26), .Y (n_122));
  OAI21X1 g3481__6417(.A0 (n_34), .A1 (fifo_count[0]), .B0 (n_33), .Y
       (n_35));
  OAI21X1 g3479__5477(.A0 (w), .A1 (n_30), .B0 (n_27), .Y (n_46));
  NOR4BX1 g3484__2398(.AN (fifo_count[3]), .B (n_50), .C
       (fifo_count[1]), .D (fifo_count[2]), .Y (n_29));
  NAND2BX1 g3480__5107(.AN (n_23), .B (w), .Y (n_37));
  AOI21X1 g3485__6260(.A0 (n_7), .A1 (n_28), .B0 (n_19), .Y (n_41));
  CLKINVX2 g3488(.A (n_27), .Y (full));
  AOI21X1 g3482__4319(.A0 (w), .A1 (n_11), .B0 (n_146), .Y (n_26));
  OR4XL g3470__8428(.A (n_24), .B (n_28), .C (fifo_count[3]), .D (n_5),
       .Y (n_25));
  CLKINVX1 g3489(.A (n_23), .Y (n_27));
  OAI21X1 g3494__5526(.A0 (fifo_count[1]), .A1 (n_21), .B0 (n_50), .Y
       (n_22));
  OAI221X1 g3495__6783(.A0 (n_47), .A1 (n_61), .B0 (read_count[0]), .B1
       (n_4), .C0 (n_145), .Y (n_20));
  CLKAND2X2 g3491__3680(.A (n_12), .B (n_30), .Y (empty));
  INVXL g3493(.A (n_19), .Y (n_33));
  NOR3X1 g3477__1617(.A (n_24), .B (fifo_count[2]), .C (n_28), .Y
       (n_18));
  OR3XL g3483__2802(.A (n_24), .B (fifo_count[1]), .C (n_16), .Y
       (n_17));
  AOI21XL g3490__1705(.A0 (write_count[2]), .A1 (n_14), .B0 (n_13), .Y
       (n_15));
  MXI2XL g3496__5122(.A (n_34), .B (n_146), .S0 (w), .Y (n_19));
  NOR2XL g3492__8246(.A (n_12), .B (n_11), .Y (n_23));
  CLKINVX1 g3497(.A (n_11), .Y (n_30));
  OAI21XL g3501__7098(.A0 (n_58), .A1 (write_count[1]), .B0 (n_9), .Y
       (n_10));
  NOR2XL g3503__6131(.A (w), .B (n_146), .Y (n_50));
  INVXL g3486(.A (n_9), .Y (n_8));
  NOR2XL g3498__1881(.A (write_count[2]), .B (n_14), .Y (n_13));
  NAND2XL g3499__5115(.A (w), .B (n_7), .Y (n_24));
  MXI2XL g3502__7482(.A (n_47), .B (read_count[0]), .S0
       (read_count[1]), .Y (n_6));
  INVXL g3504(.A (n_146), .Y (n_48));
  NAND2X1 g3500__4733(.A (n_5), .B (n_42), .Y (n_11));
  NAND2XL g3507__6161(.A (n_5), .B (n_12), .Y (n_21));
  INVXL g3511(.A (n_7), .Y (n_34));
  NAND2XL g3516__2883(.A (write_count[1]), .B (n_58), .Y (n_9));
  NAND2XL g3517__2346(.A (read_count[1]), .B (n_4), .Y (n_61));
  NOR2XL g3513__1666(.A (write_count[0]), .B (write_count[2]), .Y
       (n_3));
  NOR2XL g3505__7410(.A (read_count[1]), .B (read_count[2]), .Y (n_64));
  NAND2XL g3506__6417(.A (read_count[1]), .B (read_count[2]), .Y
       (n_65));
  NOR2XL g3518__5477(.A (reset), .B (r), .Y (n_7));
  NAND2XL g3512__2398(.A (write_count[0]), .B (write_count[2]), .Y
       (n_2));
  NAND2XL g3515__5107(.A (write_count[0]), .B (write_count[1]), .Y
       (n_14));
  NOR2X2 g3508__6260(.A (fifo_count[0]), .B (fifo_count[1]), .Y (n_42));
  NAND2XL g3509__4319(.A (fifo_count[0]), .B (fifo_count[1]), .Y
       (n_28));
  CLKINVX1 g3524(.A (read_count[2]), .Y (n_4));
  CLKINVX1 g3525(.A (fifo_count[3]), .Y (n_12));
  CLKINVX1 g3522(.A (read_count[0]), .Y (n_47));
  CLKINVX1 g3519(.A (fifo_count[0]), .Y (n_16));
  CLKINVX1 g3520(.A (fifo_count[2]), .Y (n_5));
  CLKINVX1 g3527(.A (write_count[0]), .Y (n_58));
  CLKINVX1 g3523(.A (write_count[2]), .Y (n_66));
  NOR2BX1 g2(.AN (n_64), .B (n_63), .Y (n_144));
  NAND2BX1 g3610(.AN (read_count[1]), .B (read_count[2]), .Y (n_145));
  NAND2BX1 g3611(.AN (reset), .B (r), .Y (n_146));
endmodule

